package com.example.TwitterClone.models.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.List;

import static com.example.TwitterClone.constants.ErrorMessages.BLANK_CONTENT;

@Data
public class CreatePostRequest {
    // map to owner_id in the database

    private Long ownerId;

    // post id will be generated by the database

    // created will be generated by the database

    private List<String> mentions;

    @NotBlank(message = BLANK_CONTENT)
    private String content;

}
