version: '3.4'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=twitter_app
      - POSTGRES_PASSWORD=twitter_app
      - POSTGRES_DB=twitter_db
    volumes:
      - ./postgres/volumes/data/db:/var/lib/postgresql/data
    ports:
       - "5432:5432"