version: '3.4'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

  db:
    image: postgres
    environment:
      - POSTGRES_USER=twitter_app
      - POSTGRES_PASSWORD=twitter_app
      - POSTGRES_DB=twitter_db
    volumes:
      - ./postgres/volumes/data/db:/var/lib/postgresql/data
    ports:
       - 5432:5432